kursach/app_1/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', sign_out, name='signout'),
    path('generate/', GenerateResponseView.as_view(), name='generate_response'),
    path('api/tcpdump/', TcpDumpData.as_view(), name='tcp_info'),
    path('add_equipment/', AddEquipmentView.as_view(), name='add_equipment'),
    path('equipment/', EquipmentListView.as_view(), name='equipment_list'),
    path('equipment/delete/<int:pk>/', EquipmentDeleteView.as_view(), name='delete_equipment'),
]

kursach/kursach/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_1.urls'))
]

kursach/app_1/models.py
from django.db import models


class Equipment(models.Model):
    name = models.CharField(max_length=50)
    ipaddress = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"оборудование с ipaddress : {self.ipaddress}"

# Create your models here.
class TcpPacket(models.Model):
    equipment_id = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='tcp_packets')
    timestamp = models.CharField(max_length=50)
    source_ip = models.CharField(max_length=50)
    destination_ip = models.CharField(max_length=50)
    protocol = models.CharField(max_length=20)
    details = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.timestamp} {self.source_ip} -> {self.destination_ip}"

kursach/app_1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class SignUpForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': "form-control",
            'id': 'inputUsername',
            'type': 'username',
            'placeholder': 'имя пользователя'
        }),
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'inputPassword',
            'type': 'password',
            'placeholder': 'Пароль'
        })
    )
    repeat_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'id': 'ReInputPassword',
            'type': 'password',
            'placeholder': 'Повторите пароль'
        }),
    )
    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['repeat_password']

        if password != confirm_password:
            raise forms.ValidationError(
                'пароли не совпадают'
            )
    def save(self):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password']
        )
        user.save()
        auth = authenticate(**self.cleaned_data)
        return auth

class SignInForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'inputUsername',
        })
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control mt-2',
            'id': "inputPassword",
        })
    )


class SearchForm(forms.Form):
    query = forms.CharField(
        label='Поиск',
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите id оборудования'
        })
    )
    category = forms.ChoiceField(
        label='Категория',
        choices=[
            ('all', 'Все категории'),
            ('books', 'Книги'),
            ('movies', 'Фильмы'),
            ('music', 'Музыка'),
        ],
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

kursach/app_1/views.py
import re

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.views.generic import ListView
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from .forms import SignUpForm, SignInForm
from .models import TcpPacket, Equipment

from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama.llms import OllamaLLM

#регистрирует пользователя
def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



#обработка пришедших данных оборудования
@method_decorator(csrf_exempt, name='dispatch')
class TcpDumpData(APIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # забираем данные о tcp оборудовании
        packet_data = request.data.get("packet_data")
        # проверяем ipaddress
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ipaddress = x_forwarded_for.split(',')[0].strip()
        else:
            ipaddress = request.META.get('REMOTE_ADDR')

        if not packet_data:
            return JsonResponse({"status": "error", "message": "No packet data provided"}, status=400)
        # проверка на разрешенный ipaddress
        if not Equipment.objects.filter(ipaddress=ipaddress).exists():
            return JsonResponse({'status': 'error', 'message': 'your equipment not found'}, status=403)

        # Парсинг данных пакета
        parsed_data = self.parse_packet(packet_data, ipaddress)

        if parsed_data:
            # сохранение данных в бд
            self.save_packet(parsed_data)
            return JsonResponse({"status": "success", "data": parsed_data})

        return JsonResponse({"status": "error", "message": "Invalid packet format"}, status=400)

    def parse_packet(self, raw_data: str, ipaddress: str) -> dict:
        """Парсинг сырых данных из tcpdump"""
        pattern = r"(\d+:\d+:\d+\.\d+) IP (.+?) > (.+?): (.+)"
        match = re.match(pattern, raw_data)

        if not match:
            return None

        return {'tcppacket': {
                                "timestamp": match.group(1),
                                "source_ip": '.'.join(match.group(2).split(".")[:-1]) + ':' + match.group(2).split(".")[-1],
                                "destination_ip": '.'.join(match.group(3).split(".")[:-1]) + ':' + match.group(3).split(".")[-1],
                                "protocol": "IP",
                                "details": match.group(4)
                             },
                'equipment': {'ipaddress': ipaddress}
               }

    def save_packet(self, data: dict):
        """Сохранение пакета в базу данных"""

        TcpPacket.objects.create(
            equipment_id = Equipment.objects.get(ipaddress=data['equipment']['ipaddress']),
            timestamp=data['tcppacket']['timestamp'],
            source_ip=data['tcppacket']['source_ip'],
            destination_ip=data['tcppacket']['destination_ip'],
            protocol=data['tcppacket']['protocol'],
            details=data['tcppacket']['details']
        )

#Для регистрации пользователя
class SignUpView(View):
    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, 'app_1/signup.html', context={
            'form': form,
        })
    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
        return render(request, 'app_1/signup.html', context={
            'form': form,
        })
#для входа пользователя
class SignInView(View):
    def get(self, request, *args, **kwargs):
        form = SignInForm()
        return render(request, 'app_1/signin.html', context={
            'form': form,
        })
    def post(self, request, *args, **kwargs):
        form = SignInForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                form.add_error(None, 'Неправильный пароль или указанная учётная запись не существует!')
                return render(request, 'app_1/signin.html', context={'form':form})

#обработка запроса для нейросети от пользователя
@method_decorator(csrf_exempt, name='dispatch')
class GenerateResponseView(View):
    def post(self, request, *args, **kwargs):
        user_message = request.POST.get('message', '')

        # # Логика генерации ответа (пример 1)
        # response = requests.post('http://localhost:11434/api/generate', json={
        #     "model": "llama3.2",
        #     "prompt": user_message,
        #     "stream": False
        #     #добавить параметр ответа на процессоре
        # })
        # full_text = response.json()['response']
        template = """Question: {question}

        Answer: Let's think step by step. Write in Russian"""

        prompt = ChatPromptTemplate.from_template(template)

        model = OllamaLLM(model="llama3.2")

        chain = prompt | model

        full_text = chain.invoke({"question": user_message})

        full_text = re.sub(r'\*\*\s*(.*?)\s*\*\*', r'<strong>\1</strong>', full_text)

        parts = re.findall(r'(<strong>.*?</strong>[:]?|\n|\S+)', full_text)

        return JsonResponse({'parts': parts})

#главная страница
class MainView(TemplateView):

    def get(self, request, *args, **kwargs):
        return render(request, 'app_1/index.html', self.packet_list() | self.equipment_list())

    def post(self, request, *args, **kwargs):
        # получаем имя оборудования для поиска
        name_equipment = request.POST.get('query', '').strip()
        #проверка что оборудование существует
        if Equipment.objects.filter(name=name_equipment).exists():
            equipment = Equipment.objects.get(name=name_equipment)
            packets = equipment.tcp_packets.all()
            return render(request, 'app_1/show_tcp.html', {'packets': packets})
        else:
            # Передаем ошибку и данные из packet_list + equipment_list

            context = self.packet_list() | self.equipment_list()
            context['error'] = f"Оборудование '{name_equipment}' не найдено"
            return render(request, 'app_1/index.html', context)

    #вывод недавних tcpзапросов
    def packet_list(self):
        # Загружаем TcpPacket с предварительной загрузкой связанных equipment
        packets = TcpPacket.objects.select_related('equipment_id').order_by('-created_at')[:10]
        return {"packets": packets}

    #вывод оборудований
    def equipment_list(self):
        equipments = Equipment.objects.all()
        return {"equipments": equipments}


#добавление оборудования
class AddEquipmentView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'app_1/add_equipment.html')
    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        ip_address = request.POST.get('ip_address')
        if name and ip_address:
            Equipment.objects.create(
                name=name,
                ipaddress=ip_address
            )
            return redirect(reverse('index'))
        return render(request, 'app_1/add_equipment.html')

# класс для вывода оборудования
class EquipmentListView(ListView):
    model = Equipment
    template_name = 'equipment_list.html'  # Шаблон, который будем использовать
    context_object_name = 'equipments'
    success_url = reverse_lazy('equipment_list')

# класс для удаление оборудования
class EquipmentDeleteView(View):
    def post(self, request, *args, **kwargs):
        equipment = get_object_or_404(Equipment, pk=kwargs['pk'])
        equipment.delete()
        return redirect('equipment_list')

kursach/app_1/templates/app_1/add_equipment.html
<!-- templates/add_equipment.html -->
{% extends "./base.html" %}
{% load static %}
{% block title %}Добавление оборудования{% endblock %}

{% block content %}
<h2>Добавить оборудование</h2>

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="name">Имя оборудования</label>
        <input type="text" name="name" id="name" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="ip_address">IP-адрес</label>
        <input type="text" name="ip_address" id="ip_address" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-success">Добавить</button>
</form>
{% endblock %}

kursach/app_1/templates/app_1/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--    TITLE УНИКАЛЬНЫЙ -->
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="static/style.css">
  </head>
  <body style= " {% if not request.user.is_authenticated %} background: linear-gradient(rgba(255,255,255,0.1), rgba(255,255,255,0.1)),
                url('{% static 'images/green_digits.jpg' %}') center/cover no-repeat fixed;
                margin: 0;
                z-index: -1; {% endif %}">
    <!--    НАВИГАЦИЯ ВЕЗДЕ ОДИНАКОВАЯ -->
    {% include 'app_1/navbar.html' %}

    <!--    СЛАЙДЕР ТОЛЬКО НА ГЛАВНОЙ, ГДЕ-ТО ВМЕСТО НЕГО ПРОСТО ХЭДЭР, А ГДЕ-ТО ЕГО НЕТ -->
    {% block header %}{% endblock %}

    <!--    ОСНОВНОЙ БЛОК КОНТЕНТА. ВЕЗДЕ РАЗНОЕ КОЛ-ВО КОЛОНОК -->
    {% block content %}{% endblock %}

    <!--    ПАГИНАЦИЯ ГДЕ-ТО ЕСТЬ А ГДЕ-ТО НЕТУ -->
    {% block pagination %}{% endblock %}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
  </body>
</html>

kursach/app_1/templates/app_1/equipment_list.html
<!-- templates/equipment_list.html -->
{% extends "./base.html" %}
{% load static %}
{% block title %}Оборудования{% endblock %}
{% block content %}

<h2>Оборудование</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Имя</th>
            <th>IP-адрес</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for equipment in equipments %}
        <tr>
            <td>{{ equipment.name }}</td>
            <td>{{ equipment.ipaddress }}</td>
            <td>
                <form method="post" action="{% url 'delete_equipment' equipment.pk %}"
                      onsubmit="return confirm('Вы уверены, что хотите удалить это оборудование?');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

kursach/app_1/templates/app_1/index.html
{% extends './base.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}

{% block content %}
<script src="{% static 'js/chat.js' %}"></script>
<script src="{% static 'js/alert.js' %}"></script>
{#проверка на зарегистрированного пользователя    #}
{% if user.is_authenticated %}



{#чат с искуственным интелектом     #}
<div id="chat-container">
    <div id="response-box"></div>
    <input type="text" id="input-box" placeholder="Введите ваш запрос...">
    <button onclick="sendMessage()">Отправить</button>
</div>
    
{#поиск оборудования    #}
<div class="container mt-5" id="search_id_equipment">

    <form method="POST" action="{% url 'index' %}" class="mb-4">
        {% csrf_token %}
        <div class="row g-3 align-items-center">
            <!-- Поле поиска -->
            <div class="col-md-6">
                <div class="form-floating">
                    <input type="text" 
                           class="form-control" 
                           id="id_query" 
                           name="query" 
                           placeholder="">
                    <label for="id_query">Поиск оборудования</label>
                </div>
            </div>

            
            <!-- Кнопка поиска -->
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary w-100 h-100" onclick="sendEquipment()">
                    Найти
                </button>
            </div>
        </div>
    </form>
</div>

{#    ошибка при не нахождении оборудования#}
{% if error %}
<div id="error-alert" class="alert alert-danger alert-dismissible fade show" role="alert" style="position: fixed; top: 20px; right: 20px; z-index: 1050;">
    {{ error }}
</div>
{% endif %}

{#вывод информации о tcp подключениях#}
<div id="view-container-tcp"> 
    <div class="container mt-4">
        <h1>Последние пакеты</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Оборудование</th>
                    <th>Время</th>
                    <th>Источник</th>
                    <th>Назначение</th>
                    <th>Протокол</th>
                    <th>Детали</th>
                </tr>
            </thead>
            <tbody>
                {% for packet in packets %}
                <tr>
                    <td>{{ packet.equipment_id.name }}</td>
                    <td>{{ packet.timestamp }}</td>
                    <td>{{ packet.source_ip }}</td>
                    <td>{{ packet.destination_ip }}</td>
                    <td>{{ packet.protocol }}</td>
                    <td>{{ packet.details }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>  
</div>
    
{#вывод информации о добавленных оборудованиях#}
<div id="equipment_show">    
    <h2>Оборудования</h2>
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th>Название</th>
                <th>IP-адресс</th>
            </tr>
        </thead>
        <tbody>
            {% for equipment in equipments %}
            <tr class="table-info">
                <td>{{ equipment.name }}</td>
                <td>{{ equipment.ipaddress }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <div id="btns" class="row">
        {#кнопка добавления оборудования#}
        <div id='add_equipment'>
            <a href="{% url 'add_equipment' %}" class="btn btn-primary">
                Добавить оборудование
            </a>
        </div>
        
        {#кнопка удаления оборудования#}
        <div id='delete_equipment'>
            <a href="{% url 'equipment_list' %}" class="btn btn-danger">
                Удалить оборудование
            </a>
        </div>
    </div>
</div>
{# не авторизованный пользователь    #}
{% else %}
<div class="container-fluid vh-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6 text-center bg-white rounded-4 shadow-lg p-5 bg-opacity-75">
            <!-- Заголовок -->
            <div class="mb-5">
                <h2 class="display-5 fw-bold mb-3 text-primary">
                    Здравствуй, дорогой пользователь
                </h2>
                <p class="lead text-primary">
                    Хотите зарегистрироваться или войти в систему?
                </p>
            </div>

            <!-- Кнопки -->
            <div class="d-flex flex-column flex-md-row gap-4 justify-content-center align-items-center">
                {% if request.get_full_path == '/signin/' %}
                    <a href="{% url 'signin' %}"
                       class="btn btn-lg btn-primary py-3 px-5 fs-4 fw-bold shadow-sm active">
                        Войти
                    </a>
                {% else %}
                    <a href="{% url 'signin' %}"
                       class="btn btn-lg btn-primary py-3 px-5 fs-4 fw-bold shadow-sm">
                        Войти
                    </a>
                {% endif %}

                {% if request.get_full_path == '/signup/' %}
                    <a href="{% url 'signup' %}"
                       class="btn btn-lg btn-success py-3 px-5 fs-4 fw-bold shadow-sm active">
                        Регистрация
                    </a>
                {% else %}
                    <a href="{% url 'signup' %}"
                       class="btn btn-lg btn-success py-3 px-5 fs-4 fw-bold shadow-sm">
                        Регистрация
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

kursach/app_1/templates/app_1/navbar.html
{% if user.is_authenticated %}
<section class="my-navigation">
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav me-auto mb-2 mb-lg-0 d-flex"> 
                    {% if request.get_full_path == '/' %}
                        <a class="nav-link active" href="{% url 'index' %}">Главная</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'index' %}">Главная</a>
                    {% endif %}
                    {% if request.get_full_path == '/add_equipment/' %}
                        <a class="nav-link active" href="/add_equipment/">Добавить оборудование</a>
                    {% else %}
                        <a class="nav-link" href="/add_equipment/">Добавить оборудование</a>
                    {% endif %}    
                    {% if request.get_full_path == '/equipment/' %}
                        <a class="nav-link active" href="/equipment/">Удалить оборудование</a>
                    {% else %}    
                        <a class="nav-link" href="/equipment/">Удалить оборудование</a>
                    {% endif %}
                </div>

                <form class="d-flex" role="search">

                    {% if user.is_authenticated %}
                        <span class="navbar-text me-2">{{ user }}</span>
                        <a href="{% url 'signout' %}" class="btn btn-outline-light">Выход</a>
                    {% else %}
                        {% if request.get_full_path == '/signin/' %}
                            <a href="{% url 'signin' %}" class="btn btn-outline-light me-2 active">Войти</a>
                        {% else %}
                            <a href="{% url 'signin' %}" class="btn btn-outline-light me-2">Войти</a>
                        {% endif %}
                        {% if request.get_full_path == '/signup/' %}
                            <a href="{% url 'signup' %}" class="btn btn-outline-light me-2 active">Регистрация</a>
                        {% else %}
                            <a href="{% url 'signup' %}" class="btn btn-outline-light me-2">Регистрация</a>
                        {% endif %}
                    {% endif %}
                </form>
            </div>
        </div>
    </nav>
</section>
{% endif %}

kursach/app_1/templates/app_1/show_tcp.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Список TCP-пакетов{% endblock %}


{% block content %}
<h2>Список TCP-пакетов</h2>

<table class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Время</th>
            <th>Источник</th>
            <th>Назначение</th>
            <th>Протокол</th>
            <th>Оборудование</th>
            <th>IP-адрес оборудования</th>
            <th>Детали</th>
        </tr>
    </thead>
    <tbody>
        {% if packets %}
            {% for packet in packets %}
                <tr>
                    <td>{{ packet.timestamp }}</td>
                    <td>{{ packet.source_ip }}</td>
                    <td>{{ packet.destination_ip }}</td>
                    <td>{{ packet.protocol }}</td>
                    <td>
                        {% if packet.equipment_id %}
                            {{ packet.equipment_id.name }}
                        {% else %}
                            <span class="text-muted">Не указано</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if packet.equipment_id %}
                            {{ packet.equipment_id.ipaddress }}
                        {% else %}
                            <span class="text-muted">-</span>
                        {% endif %}
                    </td>
                <td>{{ packet.details }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6" class="text-center text-muted">Нет записей</td>
            </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}

kursach/app_1/templates/app_1/signin.html
{% extends './base.html' %}
{% load static %}
{% block title %}Авторизация{% endblock %}

{% block content %}
    <section class="my-registration-form">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <!--    ЭТО ХЛЕБНЫЕ КРОШКИ -->
                    <nav aria-label="breadcrumb" class="navbar navbar-expand-lg">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item text-primary"><a href="{% url 'index' %}">Главная</a></li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Форма авторизации</li>
                        </ol>
                    </nav>

                    <div class="row justify-content-center">
                        <div class="col-6 bg-white rounded-4 shadow-lg p-5 bg-opacity-75">
                            <p class="lead">Для входа укажите логин и пароль</p>
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form method="post" action="{% url 'signin' %}">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="inputUsername" class="form-label visually-hidden">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="mb-3">
                                    <label for="inputPassword" class="form-label visually-hidden">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <button type="submit" class="btn btn-primary">Войти</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}